### ISSUE TITLE
Is the module synchronous or asynchronous?

### ISSUE THREAD

**Issue by Jackyjjc** [postmanlabs/npm-cli-login#12]
The documentation is not very clear. By looking at the source, I can see that it does the login asynchronously but it doesn't accept a callback to notify the user when the login is finished?

**Comment by czardoz** [comment]
Yes, that's something that needs fixing. This module is mostly meant to be used as a CLI, which is why it doesn't accept a callback. Pull requests are welcome though! :)

**Comment by petrvecera** [comment]
+1 This would be really nice.
