### ISSUE TITLE
--quotes=true is not valid

### ISSUE THREAD

**Issue by joh-klein** [postmanlabs/npm-cli-login#14]
I was somewhat surprised, that `--quotes=true` does nothing. From reading the README that was not clear to me.

**Comment by madebysid** [comment]
Leaving out `--quotes` sets it to false, just including it will make the quotes setting true. You do not need to append it with a `=true`. Do let me know if this is not happening.

**Comment by joh-klein** [comment]
No that works, but it is somewhat confusing.
