### ISSUE TITLE
The cli does not work with node <4

### ISSUE THREAD

**Issue by elssar** [postmanlabs/npm-cli-login#4]
In node 0.12.x, [`Array.protototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) is not available, so the cli errors out.

**Comment by madebysid** [comment]
@elssar I have corrected the error by using ```Array.prototypr.indexOf``` instead of ```Array.prototype.find``` and sent a pull request to the maintainer.

**Comment by elssar** [comment]
Fixed in #5
