### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by neeraj080** [postmanlabs/npm-cli-login#7]
/var/lib/jenkins/workspace/jobname/nvm/versions/node/v0.12.10/lib/node_modules/npm-cli-login/lib/login.js:29
                var scopeWrite = lines.findIndex(function (element) {
                                       ^
TypeError: undefined is not a function
    at /var/lib/jenkins/workspace/jobname/nvm/versions/node/v0.12.10/lib/node_modules/npm-cli-login/lib/login.js:29:40
    at fs.js:334:14
    at /var/lib/jenkins/workspace/jobname/nvm/versions/node/v0.12.10/lib/node_modules/npm-cli-login/node_modules/npm-registry-client/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by czardoz** [comment]
@neeraj080 please use Node v4+

Support for Node v0.12 will be added soon.

**Comment by neeraj080** [comment]
Ok.

**Comment by madebysid** [comment]
Hey @neeraj080, A recently merged pull request #6 should fix it for Node 0.12 as well. Can you try to install the latest version of `npm-cli-login` (0.0.10) and try again?
